### ISSUE TITLE
Problem installing another version Of MacOs

### ISSUE THREAD

**Issue by juanpy0223** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#1]
Hello, I installed Big Sur, and it works ok, but when I try to boot High Sierra, Mojave or Catalina, it only restarts, instead of booting installer.... Any sugestion?

The apps Im using now on my Lenovo x230t, work on Mojave and Catalina, better than in Big Sur... Thats why I would like to install Mojave or Catalina

**Comment by yusufklncc** [comment]
I updated EFI so you can install mojave now. I tested.

**Comment by juanpy0223** [comment]
Thank you, can you, please tell me wich setting you changed... I would like to know

**Comment by yusufklncc** [comment]
Ahaha I dont know. I just built efi quickly and carefully. Sorry about that. Feedback if you are successful

**Comment by juanpy0223** [comment]
thank you sir, much apprecieated

**Comment by yusufklncc** [comment]
u are welcome

**Comment by juanpy0223** [comment]
Hello, I could boot installers from High Sierra to Catalina... I installed both high.sierra and mojave, both working like a charm.... Thank you once more...

**Comment by yusufklncc** [comment]
This EFI for e570 but i'm glad if it worked for you
