### ISSUE TITLE
What makes the card reader work?

### ISSUE THREAD

**Issue by ftphikari** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#10]
What specific change makes the card reader work? I have a an L570 on Monterey with the same card reader, but have no idea how to make it work.

**Comment by yusufklncc** [comment]
In DeviceProperties. U can use these codes.
![image](https://user-images.githubusercontent.com/78423442/227321712-e60317fe-2523-4d02-9ff0-9be616fdeb9d.png)

**Comment by ftphikari** [comment]
Thanks, I'm already going that, but it still doesn't work. I did insert my own Pci values from `gfxutil` as well:
```
07:00.0 1217:8621 /PCI0@0/RP12@1D,3/PXSX@0 = PciRoot(0x0)/Pci(0x1D,0x3)/Pci(0x0,0x0)
```
since `dspci` said this was my SD card address:
```
07:00.0 SD Host controller [0805]: O2 Micro, Inc. SD/MMC Card Reader Controller [1217:8621] (rev 01) (subsys 17aa:2249)
```

**Comment by ftphikari** [comment]
So my device looks like this:

![Screen Shot 2023-03-23 at 22 20 42](https://user-images.githubusercontent.com/92269215/227343349-1c64d248-0708-4410-bd83-bcb9bd1f8407.png)

**Comment by ftphikari** [comment]
However if I check in IORegistryExplorer, I see that `built-in` is still set to 0 for it, while other values are set properly, I wonder if that has something to do with it not working..

![Screen Shot 2023-03-23 at 22 21 35](https://user-images.githubusercontent.com/92269215/227344014-398d3d50-bb95-471a-855d-e2a12165f490.png)

**Comment by ftphikari** [comment]
Hey, I was able to successfully fix the issue! It was Monterey-specific, but since you are using Big Sur you haven't noticed I guess. See relevant issue: https://github.com/dortania/OpenCore-Legacy-Patcher/issues/978
Solution was to download his [kext](https://github.com/dortania/OpenCore-Legacy-Patcher/files/8127765/CtlnaSDXC-v1.0.0.zip), put it into the kext folder and reload `config.plist`.
