### ISSUE TITLE
Sonoma Beta 1 Upgrade

### ISSUE THREAD

**Issue by Revalvier** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#11]
Look, I've tested your stuff and it seemed to be primed already for the Sonoma Beta 1 Upgrade, assuming you have a Phison-controlled NVME (Apple Native NVME like Intel ssdpeknw512g8l or similar) or any SATA SSD that uses a Phison controller like a Patriot Burst.

Try the following:

Pre-installation:

- change SMBIOS to MacbookPro15,2 (as advised directly to me by a Hackintosh dev in the discord channel)
- change serial, MLB and SMUUID
- add "-lilubetaall" to your boot-args
- update all kexts
- delete NVMEFixup.kext

Post-installation:
-Login to Apple to finish

![PXL_20230607_0312449532](https://github.com/yusufklncc/Lenovo-Thinkpad-E570-Hackintosh/assets/61492338/e0c41ab6-6152-4472-a2aa-4e0ef008b443)

DO NOT attempt this if your NVMe is not Phison-controlled. NVMeFixup is dead starting in macOS 14.

**Comment by yusufklncc** [comment]
I installed already but i didnt update github. thanks.
![E570 Sonoma](https://github.com/yusufklncc/Lenovo-Thinkpad-E570-Hackintosh/assets/78423442/7aa27b49-5c74-47f0-894e-63f638387134)

**Comment by yusufklncc** [comment]
and im using 14,1 SMBIOS rn.

**Comment by Revalvier** [comment]
The Hackintosh devs advised on that. said to use MacbookPro15,2 as 14,1 may get blocked in getting OTA. Nonetheless, great work as always.

**Comment by yusufklncc** [comment]
I'll switch if needed in later versions, but I'll continue to use 14,1 for now. Thanks

**Comment by yusufklncc** [comment]
Repo updated. 👍 @Revalvier
