### ISSUE TITLE
ACPI-Patch

### ISSUE THREAD

**Issue by damieai** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#12]
where can I know what value I should fill in here to replace it
![Snipaste_2023-07-12_07-43-24](https://github.com/yusufklncc/Lenovo-Thinkpad-E570-Hackintosh/assets/103806899/aed8b298-e24d-4f62-acc7-8e7edbf9b7eb)

**Comment by damieai** [comment]
oh i know the reason 16 hexadecimal but how do I know what device name I need to substitute

**Comment by yusufklncc** [comment]
Are you asking about your own computer?
