### ISSUE TITLE
EFI

### ISSUE THREAD

**Issue by rigr** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#13]
Sorry, maybe I'm blind, but I can't source the EFI folder needed for this step:
"Copy downloaded EFI folder to EFI partititon."
Please help me..

**Comment by rigr** [comment]
oh, just downloaded the EFI folder from https://github.com/yusufklncc/Lenovo-Thinkpad-E570-Hackintosh/issues/8#issue-1275692571 and hope it will work.
Thanks for all your work!

**Comment by yusufklncc** [comment]
https://github.com/yusufklncc/Lenovo-Thinkpad-E570-Hackintosh/releases

**Comment by rigr** [comment]
Thank you!

**Comment by rigr** [comment]
Yusuf,  

I have a E570 with the same characteristics as yours, it seems.
On my USB install drive I have a EFI-partition, therein is the EFI folder, inside is
/BOOT and
/OC

inside /BOOT is BOOTx64.efi and
inside /OC are folders (ACPI,Drivers, Kexts,Resources,Tools), config.plist and OpenCore.efi

would you mind to share your config.plist from the USB drive, please? My install only reads for a short while (a few seconds) from the USB drive, then stops...
Sorry, my last hackintosh was a MSI wind a LOONG while back. :)
Thank you and best regards
Richard

**Comment by yusufklncc** [comment]
Can you send me a video of problem? from telegram.

**Comment by rigr** [comment]
Yusuf thank you, I think a video showing the install screen stuck for many minutes will not help. :)
I think I just need the config.plist to put inside the /EFI/OC/ folder of my USB stick. 
In fact, sharing a zip file containing all that is needed for the EFI-partition of the USB drive would be great. The file you linked to above does not contain the config.plist file.

**Comment by yusufklncc** [comment]
HOW? I am not understanding you. Release contain the config file.

**Comment by rigr** [comment]
Oh, sorry, Yusuf, I have to apologise - you are right, everything is there! I was wrong and confused it with a different EFI-folder I downloaded. Please excuse me...

**Comment by rigr** [comment]
Yusuf, I hope you don't mind me asking another question. 
In your tutorial after setting the serial you write:

_Search MacBookPro15,1 and replace Type > SystemProductName, Serial > SystemSerialNumber, Board Serial > MLB and SmUUID > SystemUUID values. Now we will set our ROM value._

Please tell me WHERE to search and edit those values. Thank you!

**Comment by yusufklncc** [comment]
In config file with text edit. Win + F key combination.

**Comment by rigr** [comment]
ok, thank you for your personal support! :)
