### ISSUE TITLE
not an issue, but VGA is working

### ISSUE THREAD

**Issue by juanpy0223** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#2]
it surprised me, that VGA is working because it doesnot exist on real macs

**Comment by yusufklncc** [comment]
Yeah when i patched ports it worked perfect.

**Comment by juanpy0223** [comment]
My respect to you sir

**Comment by yusufklncc** [comment]
Thanks <3

**Comment by rigr** [comment]
Please allow me to ask - what version did you have installed, when VGA and hdmi worked? I have Ventura and followed the instruction for installation and all works fine apart from VGA and HDMI.
Thank you!
BTW: VGA and hdmi work fine on my E570 running Windows.
