### ISSUE TITLE
Issue with intel wifi card

### ISSUE THREAD

**Issue by juanpy0223** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#3]
Hello, I install a 7265 intel wifi card, I load the kexts both in folder and in plist... I can even connect to wifi but it wont let me surf on the internet, when I open the safari browser it says that I dont have internet, by the way, the bluetooth works fine.

**Comment by juanpy0223** [comment]
By the way, I can only use it on Big Sur, because one must set SecureBoot to Default, and Mojave/Catalina only boots and Secureboot is disabled, do you know a solution or do I have to order a bcm94360ng?

**Comment by yusufklncc** [comment]
Use new version of kext and in Mojave try to set j140k or j230k securebootmodel.

**Comment by juanpy0223** [comment]
Thank you, I will try

**Comment by juanpy0223** [comment]
Hello, securebootmodel = j140k, worked both in mojave and catalina, thanks....

Also, I added the yogaSMC.kext, for fan speed reading, but it didnt work, do you have any idea or suggestion?

**Comment by yusufklncc** [comment]
Add SMC SuperIO and Processor. If it doesn't work. I don't think it will work.

**Comment by juanpy0223** [comment]
Ok thank you

**Comment by juanpy0223** [comment]
Hello, im having a problem with wifi in Catalina, after sleep, it does not show, can I use itlwm.kext instead of airportitlwm.kext, and do I have to change securebootmodel settings, to avoid booting problems?

**Comment by yusufklncc** [comment]
Try darkwake=8 boot-arg

**Comment by juanpy0223** [comment]
Thanks

**Comment by yusufklncc** [comment]
Did it work?

**Comment by juanpy0223** [comment]
No sir it did not, any other suggestion?

**Comment by juanpy0223** [comment]
Im going to buy bcm94360ng, wich works natively both in mac and windows 10, and needs no tweeking, kexts or boot-arg 🤗

**Comment by juanpy0223** [comment]
I also.have an A+E adapter and a few airport cards taken from actual macbookpros but the adapter is too big, no room for it
