### ISSUE TITLE
macOS Sierra download

### ISSUE THREAD

**Issue by juanpy0223** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#4]
Hello, can you provide the link to download, Sierra Dmg file?

I tried with to install it via wifi with prebooter, but it never started downloading

**Comment by yusufklncc** [comment]
You can use my Sierra Image.
https://drive.google.com/file/d/1KKRlAO9_OuK_KH_nEDhxxWHWMd2-a-fU/view

**Comment by juanpy0223** [comment]
Thank you... Also I tried the last EFI you uploaded, and it says, "ACPI 1 BORKED", the old one works like a charm!!!

**Comment by yusufklncc** [comment]
I wanted to fix the error, but I accidentally broke OpenCore :) I'm getting the same error right now and my computer won't boot.  I don't have another computer right now.  I'll fix it in a few hours.

**Comment by yusufklncc** [comment]
The problem solved @juanpy0223
