### ISSUE TITLE
About Wifi Compatibility

### ISSUE THREAD

**Issue by juanpy0223** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#5]
Hello, I will like to know if DW1820A wifi card works ok on windows

**Comment by yusufklncc** [comment]
Hi. Works fine on windows.

**Comment by yusufklncc** [comment]
I added the drivers I used to the repo

**Comment by juanpy0223** [comment]
thanks

**Comment by yusufklncc** [comment]
@juanpy0223 i will update my EFI today or tomorrow.
