### ISSUE TITLE
About USB

### ISSUE THREAD

**Issue by Felix-awesome** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#6]
Hi, thanks for your contributions. I download lastest release EFI, but USB don't work in my computer(thinkpad e570), and the macos version is 12.4(Monterey) .

**Comment by Lorys89** [comment]
try this
[EFI.zip](https://github.com/yusufklncc/Lenovo-Thinkpad-E570-Hackintosh/files/8933188/EFI.zip)

**Comment by Revalvier** [comment]
for the usb, use USBMap by corpnewt, replace the USBMap.kext with a generated dummy, then reboot. Do the map from there and generate the USBMap.kext, lastly, replace the dummy USBMap.kext with your tailored USBMap.kext

**Comment by yusufklncc** [comment]
> Hi, thanks for your contributions. I download lastest release EFI, but USB don't work in my computer(thinkpad e570), and the macos version is 12.4(Monterey) .

EFI is perfect now. USB ports are fixed.
