### ISSUE TITLE
Nvidia 940MX reintroduction

### ISSUE THREAD

**Issue by Revalvier** [relaxewdy/Lenovo-Thinkpad-E570-Hackintosh#9]
I've checked with OCLP and they managed to sneak in support for Nvidia 940MX. You wanna try using the 940MX?

-use OCLP
-disable SIP completely
-disable Intel UHD 620
-force Nvidia Web Drivers with the help of OCLP
-add all necessary bootflags

**Comment by yusufklncc** [comment]
How can i use external gpu? how can i disable igpu? Did you tested? Lastly my lenovo doesnt have nvidia card sadly.
